DiemdanhHocvien/Controllers/ClassController.cs
using DiemdanhHocvien.CustomAuthentication;
using DiemdanhHocvien.DataAccess;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.UI.WebControls;




namespace DiemdanhHocvien.Controllers
{

    //[CustomAuthorize(Roles = "superadmin,admin,user,leader")]   
    [Authorize]
    public class ClassController : Controller
    {

        private AuthenticationDB db = new AuthenticationDB();

        // GET: addStudent/5
        public ActionResult addStudent(int id)
        {
            var lstStudent = db.students.ToList();
            List<string> lstnameClass = new List<string>();

            foreach (var item in lstStudent)
            {
                var nameClass = db.classes.Where(x => x.id == item.classId).Select(x => x.className).FirstOrDefault();
                if (nameClass != null)
                {

                    lstnameClass.Add(nameClass);
                }
                else
                {
                    lstnameClass.Add("null");
                }
            }
            ViewBag.lstnameClass = lstnameClass;
            ViewBag.classId = id;

            return View(lstStudent);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult addStudent(List<int> lstStudent, int classId)
        {
            if (ModelState.IsValid)
            {
                //db.students.Add(student);

                foreach (var item in lstStudent)
                {
                    db.students.Find(item).classId = classId;
                    db.SaveChanges();
                }

                ViewBag.quantity = lstStudent.Count;
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [CustomAuthorize(Roles = "superadmin,admin,user,leader")]
        // GET: Class
        public ActionResult Index()
        {
            //List all classs
            var lstClass = db.classes.ToList();
            //count student have in class
            List<int> soluong = new List<int>();

            foreach (var item in lstClass)
            {
                var countStud = db.students.Where(x => x.classId == item.id).Count();
                soluong.Add(countStud);
            }
            ViewBag.soluong = soluong;
            return View(lstClass);
        }



        // GET: Class/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Class @class = db.classes.Find(id);
            if (@class == null)
            {
                return HttpNotFound();
            }

            //tim hoc vien thuoc hop
            List<Student> studentsOfClass = new List<Student>();
            foreach (var item in db.students.ToList())
            {
                if (item.classId == id)
                {
                    studentsOfClass.Add(item);
                }
            }
            ViewBag.studentsOfClass = studentsOfClass;
            return View(@class);
        }

        // GET: Class/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Class/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,className,codeName,startDate,endDate,dayOfWeek,userId")] Class @class, List<int> dayOfWeek)
        {
            if (ModelState.IsValid && dayOfWeek != null)
            {
                List<string> l2 = dayOfWeek.ConvertAll<string>(x => x.ToString());

                @class.dayOfWeek = string.Join(",", l2);
                db.classes.Add(@class);
                db.SaveChanges();
                return RedirectToAction("Index","home");
            }

            return View(@class);
        }

        // GET: Class/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Class @class = db.classes.Find(id);
            if (@class == null)
            {
                return HttpNotFound();
            }
            return View(@class);
        }

        // POST: Class/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,className,codeName,startDate,endDate ,userId")] Class @class, List<int> dayOfWeek)
        {
            if (ModelState.IsValid)
            {
                List<string> l2 = dayOfWeek.ConvertAll<string>(x => x.ToString());

                @class.dayOfWeek = string.Join(",", l2);
                db.Entry(@class).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(@class);
        }

        // GET: Class/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Class @class = db.classes.Find(id);
            if (@class == null)
            {
                return HttpNotFound();
            }
            return View(@class);
        }

        // POST: Class/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Class @class = db.classes.Find(id);
            db.classes.Remove(@class);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteStudent(int id)
        {
            db.students.Find(id).classId = 0;
            db.SaveChanges();
            return new HttpStatusCodeResult(System.Net.HttpStatusCode.OK);

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DiemdanhHocvien/Controllers/StudentController.cs
using DiemdanhHocvien.CustomAuthentication;
using DiemdanhHocvien.DataAccess;
using DiemdanhHocvien.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace DiemdanhHocvien.Controllers
{
    [CustomAuthorize(Roles = "superadmin,admin,user,leader,teacher")]
    public class StudentController : Controller
    {
        private AuthenticationDB db = new AuthenticationDB();



        // GET: Student
        public ActionResult Index()
        {
            List<Student> listStudent = new List<Student>();

            HttpCookie authCookie = Request.Cookies["Cookie1"];
            if (authCookie != null)
            {
                FormsAuthenticationTicket authTicket = FormsAuthentication.Decrypt(authCookie.Value);

                var serializeModel = JsonConvert.DeserializeObject<CustomSerializeModel>(authTicket.UserData);
                CustomPrincipal principal = new CustomPrincipal(authTicket.Name);
                principal.UserId = serializeModel.UserId;
                
                //id is iduser
                var u = db.Users.Find(principal.UserId);
                string role = u.Roles.FirstOrDefault().RoleName;
                //set authen 
                if (role == "teacher" && role != null)
                {
                    var listClass = db.classes.Where(x => x.userId == u.UserId).ToList();
                    foreach (var item in listClass)
                    {
                        List<Student> students = db.students.Where(x => x.classId == item.id).ToList();
                        listStudent.AddRange(students);
                    }
                    //list studetn not class or class null empty
                    foreach (var item in db.students.ToList())
                    {
                        if (db.classes.Find(item.classId) == null)
                        {
                            listStudent.Add(item);
                        }
                    }

                }
                else if (role == "admin" || role == "superadmin" || role == "admin" || role == "leader")
                {
                    listStudent.AddRange(db.students.ToList());
                }
                else
                {
                    listStudent = null;
                }
                //return listStudent;
            }


            return View(listStudent);
        }

        // GET: Student/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }

            // sinh vien hoc lớp nào
            var classOfStud = db.classes.Where(x => x.id == student.classId).FirstOrDefault();
            ViewBag.classOfStud = classOfStud;
            // giáo viên dạy lớp
            ViewBag.teacherOfStud = db.Teachers.Where(x => x.id == classOfStud.userId).FirstOrDefault();
            // số ngày điểm danh
            var AtteOfStud = db.attendences.Where(x => x.studentId == student.id).ToList();
            ViewBag.countDateAtteOfStud = AtteOfStud.Count();
            // số ngày vắng
            ViewBag.countOrderFalse = AtteOfStud.Where(x => x.order == 0).Count();
            // chi tiết vắng
            //ngày - lý do - lớp 
            ViewBag.orderFalse = AtteOfStud.Where(x => x.order == 0).Select(s => new { s.time, s.description, s.order });
            // số ngày điểm danh ngoài giờ
            var startDate = classOfStud.startDate.Date;
            var endDate = classOfStud.endDate.Date;
            List<int> dayOfWeek = classOfStud.dayOfWeek.Split(',').Select(Int32.Parse).ToList();
            ViewBag.dayOfWeek = dayOfWeek;
            List<Attendence> attenDateOT = new List<Attendence>();
            List<Attendence> attenDateTrue = new List<Attendence>();
            List<Attendence> attenDateFalse = new List<Attendence>();

            for (DateTime date = startDate; date <= endDate; date = date.AddDays(1))
            {
                var a = AtteOfStud.Where(x => x.createTime.Date == date.Date && x.studentId == id).FirstOrDefault();
                if (a != null)
                {

                    if (dayOfWeek.Contains(((int)date.DayOfWeek)) == true)
                    {
                        if(a.order > 0)
                        {
                            attenDateTrue.Add(a);
                        }
                        else
                        {
                            attenDateFalse.Add(a);
                        }
                    }
                    else
                    {
                        attenDateOT.Add(a);
                    }
                }
            }
            

            // những ngày điểm danh 
            ViewBag.attenDateTrue = attenDateTrue;
            // những ngày KHONG điểm danh 
            ViewBag.attenDateFalse = attenDateFalse;
            // số ngày điểm danh ngoài giờ
            ViewBag.attenDateOT = attenDateOT;
            // chi tiết vắng
            //ngày - lý do - lớp 

            return View(student);
        }

        // GET: Student/Create
        public ActionResult Create()
        {
            ViewBag.parents = db.parents.ToList();

            return View();
        }

        // POST: Student/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,lastName,firstName,holyName,BOD,numPhone,email,parentId,classId")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.students.Add(student);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(student);
        }

        // GET: Student/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }

            ViewBag.parents = db.parents.ToList();

            student.BOD.GetDateTimeFormats();
            return View(student);
        }

        // POST: Student/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,lastName,firstName,holyName,BOD,numPhone,email,parentId,classId")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Entry(student).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(student);
        }

        // GET: Student/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Student/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Student student = db.students.Find(id);
            db.students.Remove(student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DiemdanhHocvien/Controllers/api/ClassController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using DiemdanhHocvien.DataAccess;

namespace DiemdanhHocvien.Controllers.api
{
    public class ClassController : ApiController
    {
        private AuthenticationDB db = new AuthenticationDB();

        // GET: api/Class
        public IQueryable<Class> Getclasses()
        {
            return db.classes;
        }

        // GET: api/Class/5
        [ResponseType(typeof(Class))]
        public IHttpActionResult GetClass(int id)
        {
            Class @class = db.classes.Find(id);
            if (@class == null)
            {
                return NotFound();
            }

            return Ok(@class);
        }

        // PUT: api/Class/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutClass(int id, Class @class)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != @class.id)
            {
                return BadRequest();
            }

            db.Entry(@class).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ClassExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Class
        [ResponseType(typeof(Class))]
        public IHttpActionResult PostClass(Class @class)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.classes.Add(@class);
            db.SaveChanges();

            return CreatedAtRoute("DefaultApi", new { id = @class.id }, @class);
        }

        // DELETE: api/Class/5
        [ResponseType(typeof(Class))]
        public IHttpActionResult DeleteClass(int id)
        {
            Class @class = db.classes.Find(id);
            if (@class == null)
            {
                return NotFound();
            }

            db.classes.Remove(@class);
            db.SaveChanges();

            return Ok(@class);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool ClassExists(int id)
        {
            return db.classes.Count(e => e.id == id) > 0;
        }
    }
}

DiemdanhHocvien/Views/Class/Details.cshtml
@model DiemdanhHocvien.DataAccess.Class

@{
    ViewBag.Title = "Details";
}


<div class="container-fluid" id="container-wrapper">
    <div class="row mb-2">
        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card h-100">
                <div class="card-body">
                    <div class="row align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-uppercase mb-1">Class Name</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">@Html.DisplayFor(model => model.className) </div>
                            <div class="mt-2 mb-0 text-muted text-xs">
                                <div class="text-xs font-weight-bold text-uppercase mb-1">Code Name</div>
                                <span class="text-success mr-2"> @Html.DisplayFor(model => model.codeName)</span>

                            </div>
                        </div>
                        <div class="col-auto">
                            <a title="Edit" href="@Url.Action("Edit", "Class", new { id = Model.id })" class="btn btn-secondary">
                                <i class="fas fa-fw fa-edit"></i>
                            </a>
                            <p class="text-center">edit</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Earnings (Annual) Card Example -->
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card h-100">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col   d-flex justify-content-start">
                            <div>

                                <div class="text-xs font-weight-bold text-uppercase mb-1">Start Date</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">@Model.startDate.ToString("dd-MM-yyyy")</div>
                                <div class="text-xs font-weight-bold text-uppercase mb-1">End Date</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">@Model.endDate.ToString("dd-MM-yyyy") </div>
                            </div>

                        </div>
                        <div class="col d-flex justify-content-end">
                            <div class="mt-2 mb-0 text-muted text-xs">
                                <div class="text-xs font-weight-bold mb-1">Day Of Week</div>
                                @*@Html.DisplayFor(modelItem => item.dayOfWeek)*@
                                @{ List<int> dayof = Model.dayOfWeek.Split(',').Select(Int32.Parse).ToList(); }
                                @*@dayof[0]*@
                                @foreach (var day in dayof)
                                {

                                    switch (day)
                                    {
                                        case 0:
                                            <button class="btn btn-success"> <span>CN</span></button>
                                            break;
                                        case 1:
                                            <button class="btn btn-success"> <span>2</span></button>
                                            break;
                                        case 2:
                                            <button class="btn btn-success"> <span>3</span></button>
                                            break;
                                        case 3:
                                            <button class="btn btn-success"> <span>4</span></button>
                                            break;
                                        case 4:
                                            <button class="btn btn-success"> <span>5</span></button>
                                            break;
                                        case 5:
                                            <button class="btn btn-success"> <span>6</span></button>
                                            break;
                                        case 6:
                                            <button class="btn btn-success"> <span>7</span></button>
                                            break;

                                        default:
                                            break;
                                    }
                                }
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- New User Card Example -->
        <div class="col-xl-2 col-md-6 mb-4">
            <div class="card h-100">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-uppercase mb-1">Count Student</div>
                            <div class=" count h5 mb-0 mr-3 font-weight-bold text-gray-800" >    </div>
                            <div class="mt-2 mb-0 text-muted text-xs">
                                <span class="text-success mr-2"><i class="fas fa-arrow-up"></i> 20.4%</span>
                                <span>Since last month</span>
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-users fa-2x text-info"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Pending Requests Card Example -->
        <div class="col-xl-2 col-md-6 mb-4">
            <div class="card h-100">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <img class="img-profile rounded-circle" src="/Assets/dashboard/img/boy.png" style="width: 50%">
                        </div>
                        <div class="col-auto">
                            @*<i class="fas fa-comments fa-2x text-warning"></i>*@
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="table-responsive p-3">
            <table class="table align-items-center table-flush table-hover" id="dataTableHover">
                <thead class="thead-light">
                    <tr>
                        <th>
                            lastName
                        </th>
                        <th>
                            firstName
                        </th>
                        <th>
                            holyName
                        </th>
                        <th>
                            BOD
                        </th>
                        <th>
                            numPhone
                        </th>
                        <th>
                            email
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>
                            lastName
                        </th>
                        <th>
                            firstName
                        </th>
                        <th>
                            holyName
                        </th>
                        <th>
                            BOD
                        </th>
                        <th>
                            numPhone
                        </th>
                        <th>
                            email
                        </th>
                        <th></th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in ViewBag.studentsOfClass)
                    {
                        <tr>
                            <td>
                                @item.lastName
                            </td>
                            <td>
                                @item.firstName
                            </td>
                            <td>
                                @item.holyName
                            </td>
                            <td>
                                @item.BOD
                            </td>
                            <td>
                                @item.numPhone
                            </td>
                            <td>
                                @item.email
                            </td>
                            <td>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default " data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fas fa-fw fa-ellipsis-v"></i>
                                    </button>
                                    <div class="dropdown-menu">
                                        <a title="Edit" href="@Url.Action("Edit","Student",new { id = item.id})" class="btn btn-secondary">
                                            <i class="fas fa-fw fa-edit"></i>
                                        </a>
                                        <a title="Details" href="@Url.Action("details","student",new { id = item.id})" class="btn btn-warning">
                                            <i class="fas fa-fw fa-fingerprint"></i>
                                        </a>
                                        <a title="Delete" class="btn btn-danger DeleteStudent">
                                            <i class="fas fa-fw fa-trash-alt"></i>
                                        </a>

                                    </div>
                                </div>


                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

    </div>
</div>



@section _Header{
    <link href="~/Assets/dashboard/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
}
@section _Footer{

    @*action Name for *@
    <script>
        $("#actionName").text("DeTails Class")
    </script>

    <!-- Page level plugins -->
    <script src="~/Assets/dashboard/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Assets/dashboard/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script>
        $(document).ready(function () {
            $('#dataTableHover').DataTable(); // ID From dataTable with Hover
            $(".count").append($('#dataTableHover').DataTable().rows().count());
        });
    </script>

    <script>
        $(document).delegate('.DeleteStudent', 'click', function (e) {

            e.preventDefault();
            var id =$(this).data("id");
            @*@{var id =}id{ ;}*@

            @*alert($(this).data("id"));*@
            $.ajax({
                    type: "post",
                    url: "@Url.Action("DeleteStudent", "class")",
                    ajaxasync: true,
                    data: { id: $(this).data("id") },
                    success: function () {

                        alert("success");
                        location.reload();
                        // Perform redirect
                        @*window.location.replace("@Html.Action("details","class")");*@
                    },
                    error: function (data) {
                        alert(data.x);
                    }
                });
        });
    </script>
}